"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-09-27 10:12:20.220861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('short_name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('collector_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('raw_api_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('case_number', sa.Text(), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('court', sa.Text(), nullable=True),
    sa.Column('verdict_type', sa.Text(), nullable=True),
    sa.Column('instance_tier', sa.SmallInteger(), nullable=True),
    sa.Column('plaintiffs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('defendants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('case_type', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('lower_body_text', sa.Text(), nullable=True),
    sa.Column('provisions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('isbn', sa.Text(), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('appeal_outcome', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True),
    sa.Column('fts_is', postgresql.TSVECTOR(), nullable=True),
    sa.Column('cited_provisions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verdict_filename', sa.Text(), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_doc_source_external')
    )
    op.create_index('ix_doc_case_number', 'documents', ['case_number'], unique=False)
    op.create_index('ix_doc_case_type', 'documents', ['case_type'], unique=False)
    op.create_index('ix_doc_court', 'documents', ['court'], unique=False)
    op.create_index('ix_doc_date', 'documents', ['document_date'], unique=False)
    op.create_index('ix_doc_fts_is', 'documents', ['fts_is'], unique=False, postgresql_using='gin')
    op.create_index('ix_doc_instance_tier', 'documents', ['instance_tier'], unique=False)
    op.create_index('ix_doc_source_date', 'documents', ['source_id', 'document_date'], unique=False)
    op.create_index('ix_doc_source_id', 'documents', ['source_id'], unique=False)
    op.create_index('ix_doc_verdict_type', 'documents', ['verdict_type'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.SmallInteger(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('fts_is', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_chunk_doc_idx')
    )
    op.create_index('ix_chunk_doc_id', 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_chunk_fts_is', 'document_chunks', ['fts_is'], unique=False, postgresql_using='gin')
    op.create_table('document_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_doc_id', sa.UUID(), nullable=False),
    sa.Column('to_doc_id', sa.UUID(), nullable=False),
    sa.Column('relation', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('method', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_doc_id', 'to_doc_id', 'relation', name='uq_link_from_to_rel')
    )
    op.create_index('ix_link_from', 'document_links', ['from_doc_id'], unique=False)
    op.create_index('ix_link_to', 'document_links', ['to_doc_id'], unique=False)
    # ### end Alembic commands ###

    # DB-only objects, historically created by scripts/setup_search_indexes.py,
    # scripts/setup_provision_index.py and a raw ALTER TABLE. Kept out of
    # models.py on purpose (see env.py:_include_object).
    op.execute("""
        ALTER TABLE documents ADD COLUMN IF NOT EXISTS fts tsvector
        GENERATED ALWAYS AS (to_tsvector('simple',
            coalesce(case_number,'') || ' ' || coalesce(court,'') || ' ' ||
            coalesce(verdict_type,'') || ' ' || coalesce(summary,'') || ' ' ||
            coalesce(body_text,''))) STORED
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_doc_fts ON documents USING gin (fts)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_doc_body_trgm ON documents USING gin (body_text gin_trgm_ops)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_doc_lower_body_trgm ON documents USING gin (lower_body_text gin_trgm_ops)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_doc_summary_trgm ON documents USING gin (summary gin_trgm_ops)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_doc_case_number_trgm ON documents USING gin (case_number gin_trgm_ops)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_doc_cited_provisions ON documents USING gin (cited_provisions jsonb_path_ops)")


def downgrade() -> None:
    """Downgrade schema."""
    # DB-only objects (see upgrade()); drop before the autogenerated commands.
    op.execute("DROP INDEX IF EXISTS ix_doc_cited_provisions")
    op.execute("DROP INDEX IF EXISTS ix_doc_case_number_trgm")
    op.execute("DROP INDEX IF EXISTS ix_doc_summary_trgm")
    op.execute("DROP INDEX IF EXISTS ix_doc_lower_body_trgm")
    op.execute("DROP INDEX IF EXISTS ix_doc_body_trgm")
    op.execute("DROP INDEX IF EXISTS ix_doc_fts")
    op.execute("ALTER TABLE documents DROP COLUMN IF EXISTS fts")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_link_to', table_name='document_links')
    op.drop_index('ix_link_from', table_name='document_links')
    op.drop_table('document_links')
    op.drop_index('ix_chunk_fts_is', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('ix_chunk_doc_id', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('ix_doc_verdict_type', table_name='documents')
    op.drop_index('ix_doc_source_id', table_name='documents')
    op.drop_index('ix_doc_source_date', table_name='documents')
    op.drop_index('ix_doc_instance_tier', table_name='documents')
    op.drop_index('ix_doc_fts_is', table_name='documents', postgresql_using='gin')
    op.drop_index('ix_doc_date', table_name='documents')
    op.drop_index('ix_doc_court', table_name='documents')
    op.drop_index('ix_doc_case_type', table_name='documents')
    op.drop_index('ix_doc_case_number', table_name='documents')
    op.drop_table('documents')
    op.drop_table('sources')
    # ### end Alembic commands ###
