"""
Per-source configuration. Add one SourceConfig entry per source instead of
writing if/elif branches in the pipeline.
"""
from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path

_DATA_DIR = os.environ.get("DATA_DIR", "/Volumes/RuleOfLaw/Lausnir_Data")
MARKDOWN_DIR: str = os.path.join(_DATA_DIR, "markdown")
RAW_DIR: str = os.path.join(_DATA_DIR, "raw")


@dataclass
class PdfCrop:
    header_pt: float = 0.0
    footer_pt: float = 0.0
    skip_header_on_first: bool = False
    # Size-based heading detection (héraðsdómstólar): {pt: "## "}
    heading_sizes: dict[float, str] = field(default_factory=dict)
    # Font-based heading detection (landsréttur): substring match on font name
    # e.g. {"BoldMT": "## "} matches "TimesNewRomanPS-BoldMT"
    heading_fonts: dict[str, str] = field(default_factory=dict)


@dataclass
class SourceConfig:
    short_name: str
    display_name: str
    abbreviation: str          # used in `documents.court` column
    instance_tier: int         # 1=first, 2=appeals, 3=supreme
    has_lower_court: bool      # True if body may embed lower court text
    parse_parties: str         # 'gegn' | 'role_based' | 'none'
    verdict_type_default: str  # fallback when not detected from text
    verdict_types_allowed: list[str] = field(default_factory=lambda: [
        "Dómur", "Úrskurður", "Niðurstaða", "Álit", "Dómsúrskurður",
    ])
    case_number_prefix: str = ""   # e.g. 'E-', 'S-', '' — used for validation
    pdf_crop: PdfCrop | None = None
    h1_use_display_name: bool = False  # True → H1 uses full display_name instead of court abbreviation

    def markdown_path(self, verdict_filename: str) -> Path:
        """Full path to .md file: {MARKDOWN_DIR}/{short_name}/{verdict_filename}.md"""
        return Path(MARKDOWN_DIR) / self.short_name / f"{verdict_filename}.md"

    def pdf_path(self, verdict_filename: str) -> Path:
        """Full path to .pdf file: {RAW_DIR}/{short_name}/{verdict_filename}.pdf"""
        return Path(RAW_DIR) / self.short_name / f"{verdict_filename}.pdf"


# ─── Registry ────────────────────────────────────────────────────────────────

_SOURCES: list[SourceConfig] = [
    SourceConfig(
        short_name="haestirettur",
        display_name="Hæstiréttur",
        abbreviation="Hrd.",
        instance_tier=3,
        has_lower_court=True,
        parse_parties="gegn",
        verdict_type_default="Dómur",
        case_number_prefix="",
    ),
    SourceConfig(
        short_name="landsrettur",
        display_name="Landsréttur",
        abbreviation="Lrd.",
        instance_tier=2,
        has_lower_court=True,
        parse_parties="gegn",
        verdict_type_default="Dómur",
        case_number_prefix="",
        pdf_crop=PdfCrop(
            header_pt=0.0,
            footer_pt=65.0,
            skip_header_on_first=False,
            # "Bold" matches both old PDFs (Times New Roman,Bold / Times New Roman Bold,Bol)
            # and new PDFs (TimesNewRomanPS-BoldMT). Italic variants are excluded by
            # _heading_marker() — see extractor.py.
            heading_fonts={"Bold": "## "},
        ),
    ),
    SourceConfig(
        short_name="heradsdomstolar",
        display_name="Héraðsdómstólar",
        abbreviation="Hérd.",  # prefix — full abbr includes location, e.g. 'Hérd. Rvk.'
        instance_tier=1,
        has_lower_court=False,
        parse_parties="role_based",
        verdict_type_default="Dómur",
        case_number_prefix="",
        pdf_crop=PdfCrop(
            header_pt=65.0,
            footer_pt=62.0,
            skip_header_on_first=True,
            # Section headings are 12pt bold — same size as body text, so font-based
            # detection is needed. "Bold" matches TimesNewRomanPS-BoldMT and similar.
            heading_fonts={"Bold": "## "},
        ),
    ),
    SourceConfig(
        short_name="felagsdomur",
        display_name="Félagsdómur",
        abbreviation="Féld.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="gegn",
        verdict_type_default="Dómur",
        verdict_types_allowed=["Dómur", "Úrskurður", "Ákvörðun"],
        case_number_prefix="",
        pdf_crop=PdfCrop(
            header_pt=0.0,
            footer_pt=65.0,
            skip_header_on_first=False,
            heading_fonts={"Bold": "## "},
        ),
    ),
    SourceConfig(
        short_name="samkeppni",
        display_name="Samkeppniseftirlitið",
        abbreviation="SKE",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Ákvörðun",
        verdict_types_allowed=["Ákvörðun", "Úrskurður", "Álit"],
        case_number_prefix="",
        pdf_crop=PdfCrop(
            header_pt=0.0,
            footer_pt=40.0,
            skip_header_on_first=False,
            heading_fonts={"Bold": "## "},
        ),
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="fjolmidlanefnd",
        display_name="Fjölmiðlanefnd",
        abbreviation="FMN.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Ákvörðun",
        verdict_types_allowed=["Ákvörðun", "Álit"],
        case_number_prefix="",
        pdf_crop=PdfCrop(
            header_pt=60.0,
            footer_pt=40.0,
            skip_header_on_first=False,
            heading_fonts={"Bold": "## "},
        ),
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="fjarskiptastofa",
        display_name="Fjarskiptastofa",
        abbreviation="FST.",          # PFS. fyrir pre-2021-07-01 — sett í import script
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",         # Málsaðilar → defendants handvirkt í import script
        verdict_type_default="Ákvörðun",
        verdict_types_allowed=["Ákvörðun", "Úrskurður", "Bráðabirgðaákvörðun", "Stjórnvaldssekt", "Dómsmál"],
        case_number_prefix="",
        pdf_crop=PdfCrop(
            header_pt=60.0,
            footer_pt=40.0,
            skip_header_on_first=False,
            heading_fonts={"Bold": "## "},
        ),
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="yfirskattanefnd",
        display_name="Yfirskattanefnd",
        abbreviation="YSKN.",
        instance_tier=2,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður"],
        case_number_prefix="",
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="kaeruna_voruthjonusta",
        display_name="Kærunefnd vöru- og þjónustukaupa",
        abbreviation="KVÞ.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður"],
        case_number_prefix="",
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="samgongustofa",
        display_name="Samgöngustofa",
        abbreviation="SGS.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Ákvörðun", "Dómur"],
        case_number_prefix="",
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="urskurdarnefnd_logmanna",
        display_name="Úrskurðarnefnd lögmanna",
        abbreviation="ÚLM.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="gegn",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður"],
        case_number_prefix="",
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="uua",
        display_name="Úrskurðarnefnd umhverfis- og auðlindamála",
        abbreviation="UUA.",
        instance_tier=2,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður"],
        case_number_prefix="",
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="enf",
        display_name="Eftirlitsnefnd fasteignasala",
        abbreviation="ENF.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Álit",
        verdict_types_allowed=["Álit", "Ákvörðun", "Umburðarbréf"],
        case_number_prefix="",
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="hugverkastofa",
        display_name="Hugverkastofa",
        abbreviation="HVS.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="gegn",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=[
            "Andmæli vörumerki",
            "Áfrýjun vörumerki",
            "Niðurfelling vörumerki",
            "Endurveiting einkaleyfi",
            "Áfrýjun einkaleyfi",
            "Ógilding hönnun",
            "Ógilding vörumerki",
            "Andmæli einkaleyfi",
            "Áfrýjun hönnun",
        ],
        case_number_prefix="",
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="landsdomar",
        display_name="Landsdómur",
        abbreviation="Ld.",
        instance_tier=3,
        has_lower_court=False,
        parse_parties="gegn",
        verdict_type_default="Dómur",
        verdict_types_allowed=["Dómur", "Úrskurður"],
        case_number_prefix="",
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="malskotsbeidnir",
        display_name="Málskotsbeiðnir Hæstaréttar",
        abbreviation="Hrd. málsk.",
        instance_tier=3,
        has_lower_court=False,
        parse_parties="gegn",
        verdict_type_default="Ákvörðun",
        verdict_types_allowed=["Ákvörðun"],
    ),
    SourceConfig(
        short_name="endurupptokudomur",
        display_name="Endurupptökudómur",
        abbreviation="Eud.",
        instance_tier=3,
        has_lower_court=False,
        parse_parties="role_based",
        verdict_type_default="Úrskurður",
    ),
    SourceConfig(
        short_name="personuvernd",
        display_name="Persónuvernd",
        abbreviation="Persónuvnd.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit", "Ákvörðun", "Niðurstaða"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="umbodsmadur",
        display_name="Umboðsmaður Alþingis",
        abbreviation="UA",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Álit",
        verdict_types_allowed=["Álit", "Bréf"],
        case_number_prefix="",
        pdf_crop=None,
    ),
    SourceConfig(
        short_name="afryjunarnefnd_haskoli",
        display_name="Áfrýjunarnefnd í kærumálum háskólanema",
        abbreviation="ÁKH.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="gegn",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="knhus",
        display_name="Kærunefnd húsamála",
        abbreviation="KNHÚS",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="gegn",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="urvel",
        display_name="Úrskurðarnefnd velferðarmála - Almannatryggingar",
        abbreviation="ÚRVEL",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="kaeruna_utlend",
        display_name="Kærunefnd útlendingamála",
        abbreviation="KNU",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    # ── Úrskurðarnefnd velferðarmála – undirflokkar ───────────────────────────
    SourceConfig(
        short_name="urvel_atv",
        display_name="Úrskurðarnefnd velferðarmála - Atvinnuleysistryggingar og vinnumarkaðsaðgerðir",
        abbreviation="ÚRVEL.Atv.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="gegn",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="urvel_felag",
        display_name="Úrskurðarnefnd velferðarmála - Félagsþjónusta og húsnæðismál",
        abbreviation="ÚRVEL.Fþh.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="gegn",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="urvel_faed",
        display_name="Úrskurðarnefnd velferðarmála - Fæðingar- og foreldraorlof",
        abbreviation="ÚRVEL.Fo.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="gegn",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="urvel_greid",
        display_name="Úrskurðarnefnd velferðarmála - Greiðsluaðlögunarmál",
        abbreviation="ÚRVEL.Ga.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="gegn",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="urvel_barna",
        display_name="Úrskurðarnefnd velferðarmála - Barnaverndarmál",
        abbreviation="ÚRVEL.Bv.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="gegn",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    # ── Stærri nefndir ────────────────────────────────────────────────────────
    SourceConfig(
        short_name="mannanafnanefnd",
        display_name="Mannanafnanefnd",
        abbreviation="MNN",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="kaeruna_utbod",
        display_name="Kærunefnd útboðsmála",
        abbreviation="KÚ.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="gegn",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit", "Ákvörðun"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="urnefnd_uppl",
        display_name="Úrskurðarnefnd um upplýsingamál",
        abbreviation="ÚU.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="innvida",
        display_name="Úrskurðir á málefnasviði innviðaráðuneytisins",
        abbreviation="Ú.Ir.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="yfirfasteignamat",
        display_name="Yfirfasteignamatsnefnd",
        abbreviation="YFM.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="kaeruna_jafnr",
        display_name="Kærunefnd jafnréttismála",
        abbreviation="KJM.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="matsnefnd_eignarnam",
        display_name="Matsnefnd eignarnámsbóta",
        abbreviation="MN.Enb.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="gegn",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="endurupptakunefnd",
        display_name="Endurupptökunefnd",
        abbreviation="Enduruppt.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="urnefnd_hollusta",
        display_name="Úrskurðarnefnd samkvæmt lögum um hollustuhætti og mengunarvarnir",
        abbreviation="ÚRHOL.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="urnefnd_verdtryggt",
        display_name="Úrskurðarnefnd um leiðréttingu verðtryggðra fasteignaveðlána",
        abbreviation="ÚRVFL.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="urnefnd_raforka",
        display_name="Úrskurðarnefnd raforkumála",
        abbreviation="ÚRR.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="urnefnd_kosninga",
        display_name="Úrskurðarnefnd kosningamála",
        abbreviation="ÚRKM.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="sveitarstj_alit",
        display_name="Álit\xa0á sviði sveitarstjórnarmála",
        abbreviation="Sveitastj.M.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Álit",
        verdict_types_allowed=["Álit", "Úrskurður"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="lausn_stundar",
        display_name="Nefnd vegna lausnar um stundarsakir",
        abbreviation="Nefnd.Lausn",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="matsnefnd_lax",
        display_name="Matsnefnd samkvæmt lögum um lax- og silungsveiði",
        abbreviation="M.Lax.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    # ── Ráðuneytaúrskurðir ────────────────────────────────────────────────────
    SourceConfig(
        short_name="velferdar_raduneyti",
        display_name="Úrskurðir velferðarráðuneytisins 2011-2018",
        abbreviation="ÚRVEL.11-18",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="sjavarutv",
        display_name="Úrskurðir um sjávarútveg og fiskeldi",
        abbreviation="ÚRSJÁ.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="heilbrigdi_raduneyti",
        display_name="Úrskurðir heilbrigðisráðuneytis",
        abbreviation="Ú.Hr.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="stjornsyslu_kaerur",
        display_name="Stjórnsýslukærur - úrskurðir",
        abbreviation="Ú.SSK",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="umhverfi_raduneyti",
        display_name="Úrskurðir umhverfis-٫ orku- og loftslagsráðuneytisins",
        abbreviation="Ú.UOLr.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="matvael_land",
        display_name="Úrskurðir um matvæli og landbúnað",
        abbreviation="ÚRMAT.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="mennta_raduneyti",
        display_name="Úrskurðir mennta- og barnamálaráðuneytisins",
        abbreviation="Ú.MBr.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="landskjor",
        display_name="Úrskurðir landskjörstjórnar",
        abbreviation="LKS.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="felag_hus_raduneyti",
        display_name="Úrskurðir félags- og húsnæðismálaráðuneytisins",
        abbreviation="Ú.FHr.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="ferdathjod",
        display_name="Úrskurðir ferðaþjónusta",
        abbreviation="ÚRFÞ.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="vidskiptamal",
        display_name="Úrskurðir viðskiptamál",
        abbreviation="ÚRVM.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="innanr_utl",
        display_name="Úrskurðir innanríkisráðuneytisins á sviði útlendingamála fram til 1. janúar 2015",
        abbreviation="Ú.Ir.Ú.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="mnh_raduneyti",
        display_name="Úrskurðir á málefnasviðum menningar-٫ nýsköpunar- og háskólaráðuneytisins",
        abbreviation="Ú.MNHr.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="forseta_raduneyti",
        display_name="Úrskurðir forsætisráðuneytisins",
        abbreviation="Ú.Fr.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="kosninga_ursk",
        display_name="Úrskurðir vegna kosninga",
        abbreviation="ÚRKOSN.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
    SourceConfig(
        short_name="utanr_raduneyti",
        display_name="Úrskurðir utanríkisráðuneytisins",
        abbreviation="Ú.ur.",
        instance_tier=1,
        has_lower_court=False,
        parse_parties="none",
        verdict_type_default="Úrskurður",
        verdict_types_allowed=["Úrskurður", "Álit"],
        h1_use_display_name=True,
    ),
]

# Index by short_name for O(1) lookup
SOURCE_REGISTRY: dict[str, SourceConfig] = {s.short_name: s for s in _SOURCES}


def get_config(short_name: str) -> SourceConfig:
    try:
        return SOURCE_REGISTRY[short_name]
    except KeyError:
        raise ValueError(f"Unknown source: {short_name!r}. Add it to engine/config/sources.py")


def all_configs() -> list[SourceConfig]:
    return list(_SOURCES)
